# This reusable workflow accepts a list of hostnames to test along with files containing what paths to use for each hostname.
# This function will look for a file with the same name as the hostname with the .json extension. 
# For example, if you are testing site1.com you need the file ./testfiles/site1.com.json, the format for this file
# can be found here https://github.com/marketplace/actions/check-urls
name: Check URLs

on:
  workflow_call:
    inputs:
      webhook:
        required: true
        type: string
      hostnames:  # Should be json like array [ site1.com, site2.com ]
        required: true
        type: string
      filedir : # Where to look for the .sjon files coresspoding to each hostname
        required: true
        type: string
        
env:
  SLACK_WEBHOOK: ${{ inputs.webhook }}

jobs:
  check-urls:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hostname: ${{ fromJson(inputs.hostnames) }}
    name: Checks URLs from JSON file
    steps:
      - name: Log the action path
        run: echo "The file dir is ${{ input.filedir}}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check URLs
        uses: bythepixel/urlchecker@v0.15.0
        with:
          hostname: ${{ matrix.hostnames }}
          filename: ${{ inputs.filedir}}/${{ matrix.hostnames }}.json
